apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          env:
            - name: URI_PRENOTAZIONE
              value: http://microservizi-prenotazione.default.svc.cluster.local:8080/
            - name: URI_UTENTI
              value: http://microservizi-utenti.default.svc.cluster.local:8080/
            - name: URI_FRONTEND
              value: http://front-end.default.svc.cluster.local:8080/
          image: pievit/api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - image: rabbitmq:management
          name: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: LoadBalancer
  ports:
    - name: ui
      port: 15672
      targetPort: 15672
    - name: queue
      port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq