services:
  api-gateway:
    build:
      context: ./api-gateway/
    container_name: api-gateway
    image: pievit/api-gateway:latest
    environment:
      URI_UTENTI: http://microservizi-utenti:8080/
      URI_PRENOTAZIONE: http://microservizi-prenotazioni:8080/
      URI_FRONTED: http://front-end:8080/
    ports:
      - "8080:8080"
    networks:
      - opnet

networks:
  opnet:
    driver: bridge
