server.port=8080
spring.application.name=api-gateway
#spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.routes[0].id=microservizi-utenti-api
spring.cloud.gateway.routes[0].uri=http://microservizi-utenti.default.svc.cluster.local:8080/
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/utenti/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/utenti/(?<segment>.*), /api/v1/$\{segment}
#  SetPath=/api/v1/{var},SetPath=/api/v1/{var1}/{var2}
spring.cloud.gateway.routes[1].id=microservizi-utenti-login
spring.cloud.gateway.routes[1].uri=http://microservizi-utenti.default.svc.cluster.local:8080/
spring.cloud.gateway.routes[1].predicates[0]=Path=/login/utenti/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/login/utenti(?!/oauth2)/(?<segment>.*), /$\{segment}

spring.cloud.gateway.routes[2].id=microservizi-utenti-google
spring.cloud.gateway.routes[2].uri=http://microservizi-utenti.default.svc.cluster.local:8080/
spring.cloud.gateway.routes[2].predicates[0]=Path=/oauth2/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/oauth2/(?<segment>.*), /oauth2/$\{segment}

spring.cloud.gateway.routes[3].id=microservizi-utenti-google-2
spring.cloud.gateway.routes[3].uri=http://microservizi-utenti.default.svc.cluster.local:8080/
spring.cloud.gateway.routes[3].predicates[0]=Path=/login/oauth2/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/login/oauth2/(?<segment>.*), /login/oauth2/$\{segment}

spring.cloud.gateway.routes[4].id=microservizi-utenti-google-3
spring.cloud.gateway.routes[4].uri=http://microservizi-utenti.default.svc.cluster.local:8080/oauth2/authorization/google?continue
spring.cloud.gateway.routes[4].predicates[0]=Path=/login/utenti/oauth2/authorization/google
#spring.cloud.gateway.routes[4].filters[0]=RewritePath=/login/oauth2/(?<segment>.*), /login/oauth2/$\{segment}
#spring.cloud.kubernetes.Configuration.enabled=false

