server.port=8080
spring.application.name=api-gateway
#spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.routes[0].id=microservizi-utenti-api
spring.cloud.gateway.routes[0].uri=http://microservizi-utenti.default.svc.cluster.local:8080/api/v1/{var}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/utenti/{var}
spring.cloud.gateway.routes[1].id=microservizi-utenti-login
spring.cloud.gateway.routes[1].uri=http://microservizi-utenti.default.svc.cluster.local:8080/{var}
spring.cloud.gateway.routes[1].predicates[0]=Path=/login/utenti/{var}
spring.cloud.gateway.routes[2].id=microservizi-utenti-google
spring.cloud.gateway.routes[2].uri=http://microservizi-utenti.default.svc.cluster.local:8080/oauth2/authorization/google
spring.cloud.gateway.routes[2].predicates[0]=Path=/oauth2/authorization/google

#spring.cloud.kubernetes.Configuration.enabled=false

#zuul.routes.microservizi-utenti.path=/api/v1/utenti/**
#zuul.routes.microservizi-utenti.url=http://microservizi-utenti:8080
#zuul.routes.microservizi-utenti.sensitiveHeaders=Cookie,Set-Cookie

